### ISSUE TITLE
Add webpart page sample incorrect

### ISSUE THREAD

**Issue by Forgot-My-Name-Again** [SubPointSolutions/subpointsolutions-docs#120]
The sample on http://docs.subpointsolutions.com/spmeta2/reference/sp-foundation-definitions/webpartpagedefinition?#add-web-part-page is incomplete.
- Title is required for the WebPartPageDefinition
  --> SPMeta2.Exceptions.SPMeta2ModelValidationException: Property [Title] is not valid.
- Provisioning this sample with title set to a site (with SitePages library on O365) results in:
  --> Inner Exception: Microsoft.SharePoint.Client.ServerException: The URL 'SitePages
  /Customers-report.aspx' is invalid.  It may refer to a nonexistent file or folde
  r, or refer to a valid file or folder that is not in the current Web.

**Comment by Forgot-My-Name-Again** [comment]
any idea what is causing the invalid url error?

**Comment by SubPointSupport** [comment]
We moved it to SPMeta2 repo. Haven't checked yet.

WebPartPage provisioning error #876
https://github.com/SubPointSolutions/spmeta2/issues/876
