### ISSUE TITLE
Fix WebPartpageDefinition sample 

### ISSUE THREAD

**Issue by SubPointSupport** [SubPointSolutions/subpointsolutions-docs#123]
They should include Title for the web part pages.

http://docs.subpointsolutions.com/spmeta2/reference/sp-foundation-definitions/webpartpagedefinition?#add-web-part-page
https://www.yammer.com/spmeta2feedback/#/Threads/show?threadId=758035766

**Comment by Forgot-My-Name-Again** [comment]
#120
